
language: node_js

node_js:
  - 8

os:
  - linux
dist: trusty

cache:
  directories:
    - ${HOME}/.esy

install:
  - npm install --global esy@0.6.2
  - esy install

script:
  - esy build
  - git clone https://git.sr.ht/~lthms/coqbook.css ${HOME}/coqbook.css
  - esy html
  - cp ${HOME}/coqbook.css/coqdoc.css html

deploy:
  provider: pages
  local_dir: html
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master

